# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestTodo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTodo
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'BRYXBanner'
  pod 'Firebase'
  pod 'FirebaseDatabase'
end
